<a href="https://colab.research.google.com/github/hOshi123456/Proyecto_Hotel_Booking_Demand/blob/main/ProyectoHotelDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from google.colab import files

archivos = files.upload()

Saving hotel_bookings.csv to hotel_bookings.csv

In [3]:
import pandas as pd
import numpy as np

df = pd.read_csv("hotel_bookings.csv")

df.head()

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

In [4]:
# Tamaño del dataset
filas, columnas = df.shape

print("Cantidad de filas:", filas)
print("Cantidad de columnas:", columnas)
print("Cantidad total de celdas:", filas * columnas)

# Primeras filas
display(df.head())

# Información de las columnas
df.info()

# Valores faltantes
faltantes = pd.DataFrame({
    "Cantidad": df.isnull().sum(),
    "Porcentaje": (df.isnull().sum() / len(df)) * 100
})

faltantes = faltantes[faltantes["Cantidad"] > 0]
display(faltantes.sort_values("Cantidad", ascending=False))

# Duplicados
print("Filas duplicadas:", df.duplicated().sum())

Cantidad de filas: 119390
Cantidad de columnas: 32
Cantidad total de celdas: 3820480

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,deposit_type,agent,company,days_in_waiting_list,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,No Deposit,NaN,NaN,0,Transient,0.0,0,0,Check-Out,2015-07-01
2,Resort Hotel,0,7,2015,July,27,1,0,1,1,...,No Deposit,NaN,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
3,Resort Hotel,0,13,2015,July,27,1,0,1,1,...,No Deposit,304.0,NaN,0,Transient,75.0,0,0,Check-Out,2015-07-02
4,Resort Hotel,0,14,2015,July,27,1,0,2,2,...,No Deposit,240.0,NaN,0,Transient,98.0,0,1,Check-Out,2015-07-03

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 32 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  object
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  object
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  object
 13  country                         118902 non-null  object
 14  market_segment                  119390 non-null  object
 15  distribution_channel            119390 non-null  object
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  object
 20  assigned_room_type              119390 non-null  object
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  object
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  object
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  object
 31  reservation_status_date         119390 non-null  object
dtypes: float64(4), int64(16), object(12)
memory usage: 29.1+ MB

          Cantidad  Porcentaje
company     112593   94.306893
agent        16340   13.686238
country        488    0.408744
children         4    0.003350

Filas duplicadas: 31994

In [5]:
df_original = df.copy()
df_limpio = df.copy()

print("Copia creada correctamente")
print("Filas originales:", df_limpio.shape[0])
print("Columnas originales:", df_limpio.shape[1])

Copia creada correctamente
Filas originales: 119390
Columnas originales: 32

In [6]:
duplicados_antes = df_limpio.duplicated().sum()

df_limpio = df_limpio.drop_duplicates().reset_index(drop=True)

print("Duplicados encontrados:", duplicados_antes)
print("Filas después de eliminar duplicados:", df_limpio.shape[0])

Duplicados encontrados: 31994
Filas después de eliminar duplicados: 87396

In [7]:
#Eliminar la columna "company" ya que tiene mas del 94% de valores faltantes, imputarala no seria confiable
df_limpio = df_limpio.drop(columns=["company"])

print("Columna 'company' eliminada")
print("Cantidad de columnas:", df_limpio.shape[1])

Columna 'company' eliminada
Cantidad de columnas: 31

In [8]:
#Tratar los valores faltantes
#Para children, usamos la mediana
df_limpio["children"] = df_limpio["children"].fillna(
    df_limpio["children"].median()
)
#Para country usamos, usamos la moda
df_limpio["country"] = df_limpio["country"].fillna(
    df_limpio["country"].mode()[0]
)
#Para agent, conviene usar 0, porque generalmente indica que la reserva no fue gestionada por un agente
df_limpio["agent"] = df_limpio["agent"].fillna(0)
#Comprobar el resultado
print("Valores faltantes restantes:")
print(df_limpio.isnull().sum()[df_limpio.isnull().sum() > 0])

print("\nDimensiones actuales:")
print(df_limpio.shape)

resumen_limpieza = pd.DataFrame({
    "Tipo de dato": df_limpio.dtypes,
    "Valores faltantes": df_limpio.isnull().sum()
})

display(resumen_limpieza)

Valores faltantes restantes:
Series([], dtype: int64)

Dimensiones actuales:
(87396, 31)

                               Tipo de dato  Valores faltantes
hotel                                object                  0
is_canceled                           int64                  0
lead_time                             int64                  0
arrival_date_year                     int64                  0
arrival_date_month                   object                  0
arrival_date_week_number              int64                  0
arrival_date_day_of_month             int64                  0
stays_in_weekend_nights               int64                  0
stays_in_week_nights                  int64                  0
adults                                int64                  0
children                            float64                  0
babies                                int64                  0
meal                                 object                  0
country                              object                  0
market_segment                       object                  0
distribution_channel                 object                  0
is_repeated_guest                     int64                  0
previous_cancellations                int64                  0
previous_bookings_not_canceled        int64                  0
reserved_room_type                   object                  0
assigned_room_type                   object                  0
booking_changes                       int64                  0
deposit_type                         object                  0
agent                               float64                  0
days_in_waiting_list                  int64                  0
customer_type                        object                  0
adr                                 float64                  0
required_car_parking_spaces           int64                  0
total_of_special_requests             int64                  0
reservation_status                   object                  0
reservation_status_date              object                  0

In [9]:
print(df_limpio["reservation_status"].value_counts())

display(
    df_limpio[
        ["is_canceled", "reservation_status", "reservation_status_date"]
    ].head(15)
)

reservation_status
Check-Out    63371
Canceled     23011
No-Show       1014
Name: count, dtype: int64

    is_canceled reservation_status reservation_status_date
0             0          Check-Out              2015-07-01
1             0          Check-Out              2015-07-01
2             0          Check-Out              2015-07-02
3             0          Check-Out              2015-07-02
4             0          Check-Out              2015-07-03
5             0          Check-Out              2015-07-03
6             0          Check-Out              2015-07-03
7             1           Canceled              2015-05-06
8             1           Canceled              2015-04-22
9             1           Canceled              2015-06-23
10            0          Check-Out              2015-07-05
11            0          Check-Out              2015-07-05
12            0          Check-Out              2015-07-05
13            0          Check-Out              2015-07-05
14            0          Check-Out              2015-07-05

In [10]:
#Eliminacion de columnas con fugas de informacion
columnas_fuga = [
    "reservation_status",
    "reservation_status_date"
]

df_limpio = df_limpio.drop(columns=columnas_fuga)

print("Columnas eliminadas:", columnas_fuga)
print("Dimensiones actuales:", df_limpio.shape)

Columnas eliminadas: ['reservation_status', 'reservation_status_date']
Dimensiones actuales: (87396, 29)

In [11]:
reservas_sin_huespedes = df_limpio[
    (df_limpio["adults"] == 0) &
    (df_limpio["children"] == 0) &
    (df_limpio["babies"] == 0)
]

print("Reservas sin huéspedes:", len(reservas_sin_huespedes))

#Eliminar esas reservas sin huespedes
df_limpio = df_limpio[
    ~(
        (df_limpio["adults"] == 0) &
        (df_limpio["children"] == 0) &
        (df_limpio["babies"] == 0)
    )
].reset_index(drop=True)

print("Dimensiones después de eliminar reservas inválidas:")
print(df_limpio.shape)

#Recisamos el balance de la variable objetivo, saber cuantas reservas fueron canceladas
#y cuantas reservas no fueron canceladas
conteo_cancelaciones = df_limpio["is_canceled"].value_counts()

porcentaje_cancelaciones = (
    df_limpio["is_canceled"]
    .value_counts(normalize=True)
    .mul(100)
    .round(2)
)

print("Cantidad:")
print(conteo_cancelaciones)

print("\nPorcentaje:")
print(porcentaje_cancelaciones)
print(df_limpio.shape)
print(df_limpio["is_canceled"].value_counts())

Reservas sin huéspedes: 166
Dimensiones después de eliminar reservas inválidas:
(87230, 29)
Cantidad:
is_canceled
0    63221
1    24009
Name: count, dtype: int64

Porcentaje:
is_canceled
0    72.48
1    27.52
Name: proportion, dtype: float64
(87230, 29)
is_canceled
0    63221
1    24009
Name: count, dtype: int64

In [12]:
#Separar la variable objetivo
#La columna para predecir es is_canceled

# Variable objetivo
objetivo = "is_canceled"

# X contiene las variables predictoras
X = df_limpio.drop(columns=[objetivo])

# y contiene la respuesta que queremos predecir
y = df_limpio[objetivo]

print("Dimensiones de X:", X.shape)
print("Dimensiones de y:", y.shape)

Dimensiones de X: (87230, 28)
Dimensiones de y: (87230,)

In [13]:
#Para identificar columnas numericas y categoricas
columnas_numericas = X.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

columnas_categoricas = X.select_dtypes(
    include=["object", "category"]
).columns.tolist()

print("Columnas numéricas:", len(columnas_numericas))
print(columnas_numericas)

print("\nColumnas categóricas:", len(columnas_categoricas))
print(columnas_categoricas)

Columnas numéricas: 18
['lead_time', 'arrival_date_year', 'arrival_date_week_number', 'arrival_date_day_of_month', 'stays_in_weekend_nights', 'stays_in_week_nights', 'adults', 'children', 'babies', 'is_repeated_guest', 'previous_cancellations', 'previous_bookings_not_canceled', 'booking_changes', 'agent', 'days_in_waiting_list', 'adr', 'required_car_parking_spaces', 'total_of_special_requests']

Columnas categóricas: 10
['hotel', 'arrival_date_month', 'meal', 'country', 'market_segment', 'distribution_channel', 'reserved_room_type', 'assigned_room_type', 'deposit_type', 'customer_type']

In [14]:
#Para dividir entrenamiento y prueba
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

#(stratify=y mantiene la misma proporción de reservas canceladas y no canceladas en entrenamiento y prueba.)

#Crear el procesador
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer

# Escala las columnas numéricas
transformador_numerico = StandardScaler()

# Convierte las categorías en columnas binarias
transformador_categorico = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=True
)

# Une ambos procesos
preprocesador = ColumnTransformer(
    transformers=[
        (
            "numericas",
            transformador_numerico,
            columnas_numericas
        ),
        (
            "categoricas",
            transformador_categorico,
            columnas_categoricas
        )
    ]
)

print("Preprocesador creado correctamente")

#Transformar los datos
X_train_procesado = preprocesador.fit_transform(X_train)

X_test_procesado = preprocesador.transform(X_test)

print("Entrenamiento procesado:", X_train_procesado.shape)
print("Prueba procesada:", X_test_procesado.shape)

X_train: (69784, 28)
X_test: (17446, 28)
y_train: (69784,)
y_test: (17446,)
Preprocesador creado correctamente
Entrenamiento procesado: (69784, 245)
Prueba procesada: (17446, 245)

In [17]:
#Agente 1 Normalizador
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer


class AgenteNormalizador:
    def __init__(self, columna_objetivo="is_canceled"):
        self.columna_objetivo = columna_objetivo
        self.preprocesador = None
        self.columnas_numericas = []
        self.columnas_categoricas = []

    def limpiar_datos(self, df):
        df_limpio = df.copy()

        # Eliminar filas duplicadas
        df_limpio = df_limpio.drop_duplicates()

        # Eliminar columnas con demasiados valores faltantes
        df_limpio = df_limpio.drop(
            columns=["company"],
            errors="ignore"
        )

        # Imputar valores faltantes
        if "children" in df_limpio.columns:
            df_limpio["children"] = df_limpio["children"].fillna(
                df_limpio["children"].median()
            )

        if "country" in df_limpio.columns:
            df_limpio["country"] = df_limpio["country"].fillna(
                df_limpio["country"].mode()[0]
            )

        if "agent" in df_limpio.columns:
            df_limpio["agent"] = df_limpio["agent"].fillna(0)

        # Eliminar columnas con fuga de información
        df_limpio = df_limpio.drop(
            columns=[
                "reservation_status",
                "reservation_status_date"
            ],
            errors="ignore"
        )

        # Eliminar reservas sin huéspedes
        columnas_huespedes = {"adults", "children", "babies"}

        if columnas_huespedes.issubset(df_limpio.columns):
            df_limpio = df_limpio[
                ~(
                    (df_limpio["adults"] == 0) &
                    (df_limpio["children"] == 0) &
                    (df_limpio["babies"] == 0)
                )
            ]

        return df_limpio.reset_index(drop=True)

    def preparar_datos(self, df):
        df_limpio = self.limpiar_datos(df)

        X = df_limpio.drop(columns=[self.columna_objetivo])
        y = df_limpio[self.columna_objetivo]

        self.columnas_numericas = X.select_dtypes(
            include=["int64", "float64"]
        ).columns.tolist()

        self.columnas_categoricas = X.select_dtypes(
            include=["object", "category"]
        ).columns.tolist()

        X_train, X_test, y_train, y_test = train_test_split(
            X,
            y,
            test_size=0.20,
            random_state=42,
            stratify=y
        )

        self.preprocesador = ColumnTransformer(
            transformers=[
                (
                    "numericas",
                    StandardScaler(),
                    self.columnas_numericas
                ),
                (
                    "categoricas",
                    OneHotEncoder(
                        handle_unknown="ignore",
                        sparse_output=True
                    ),
                    self.columnas_categoricas
                )
            ]
        )

        X_train_procesado = self.preprocesador.fit_transform(X_train)
        X_test_procesado = self.preprocesador.transform(X_test)

        return {
            "df_limpio": df_limpio,
            "X_train": X_train,
            "X_test": X_test,
            "y_train": y_train,
            "y_test": y_test,
            "X_train_procesado": X_train_procesado,
            "X_test_procesado": X_test_procesado
        }

In [18]:
agente_1 = AgenteNormalizador()

resultado_agente_1 = agente_1.preparar_datos(df)

print("Agente 1 ejecutado correctamente")
print(
    "Dataset limpio:",
    resultado_agente_1["df_limpio"].shape
)
print(
    "Entrenamiento procesado:",
    resultado_agente_1["X_train_procesado"].shape
)
print(
    "Prueba procesada:",
    resultado_agente_1["X_test_procesado"].shape
)

Agente 1 ejecutado correctamente
Dataset limpio: (87230, 29)
Entrenamiento procesado: (69784, 245)
Prueba procesada: (17446, 245)

In [19]:
#Agente 2 Entrenador. Entrenará varios modelos, evaluar accuracy, precision, recall,F1 y AUC
#Seleccionará automaticamente el mejor jjsjs
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score
)

import pandas as pd


class AgenteEntrenador:
    def __init__(self):
        self.modelos = {
            "Regresión Logística": LogisticRegression(
                max_iter=1000,
                random_state=42
            ),

            "Árbol de Decisión": DecisionTreeClassifier(
                max_depth=10,
                random_state=42
            ),

            "Random Forest": RandomForestClassifier(
                n_estimators=100,
                random_state=42,
                n_jobs=-1
            )
        }

        self.resultados = []
        self.mejor_modelo = None
        self.nombre_mejor_modelo = None

    def entrenar_y_evaluar(
        self,
        X_train,
        X_test,
        y_train,
        y_test
    ):
        self.resultados = []

        for nombre, modelo in self.modelos.items():

            print(f"Entrenando: {nombre}")

            modelo.fit(X_train, y_train)

            predicciones = modelo.predict(X_test)

            probabilidades = modelo.predict_proba(X_test)[:, 1]

            resultado = {
                "Modelo": nombre,
                "Accuracy": accuracy_score(
                    y_test,
                    predicciones
                ),
                "Precision": precision_score(
                    y_test,
                    predicciones,
                    zero_division=0
                ),
                "Recall": recall_score(
                    y_test,
                    predicciones,
                    zero_division=0
                ),
                "F1 Score": f1_score(
                    y_test,
                    predicciones,
                    zero_division=0
                ),
                "AUC": roc_auc_score(
                    y_test,
                    probabilidades
                )
            }

            self.resultados.append(resultado)

        tabla_resultados = pd.DataFrame(self.resultados)

        tabla_resultados = tabla_resultados.sort_values(
            by="F1 Score",
            ascending=False
        ).reset_index(drop=True)

        self.nombre_mejor_modelo = tabla_resultados.loc[
            0,
            "Modelo"
        ]

        self.mejor_modelo = self.modelos[
            self.nombre_mejor_modelo
        ]

        return tabla_resultados

In [20]:
#Probamos el agente usando la salida del Agente 1
agente_2 = AgenteEntrenador()

tabla_resultados = agente_2.entrenar_y_evaluar(
    resultado_agente_1["X_train_procesado"],
    resultado_agente_1["X_test_procesado"],
    resultado_agente_1["y_train"],
    resultado_agente_1["y_test"]
)

print("\nComparación de modelos:")
display(tabla_resultados)

print(
    "\nMejor modelo:",
    agente_2.nombre_mejor_modelo
)

Entrenando: Regresión Logística
Entrenando: Árbol de Decisión
Entrenando: Random Forest

Comparación de modelos:

                Modelo  Accuracy  Precision    Recall  F1 Score       AUC
0        Random Forest  0.853204   0.785478  0.642024  0.706543  0.911166
1    Árbol de Decisión  0.825633   0.712253  0.614952  0.660036  0.885325
2  Regresión Logística  0.799209   0.690413  0.490421  0.573481  0.850552

Mejor modelo: Random Forest